name: Delete docs for closed PRs
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 0     # weekly

# Sets permissions of the GITHUB_TOKEN to allow modification of contents
permissions:
  contents: write

jobs:
  remove_prs:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install requirements
      run: |
        sudo apt-get install -y jq curl
        curl https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo -o ../git-filter-repo.py
    - name: Remove PRs
      run: python scripts/remove_closed_prs.py -g --cmd "python ../git-filter-repo.py"
    - name: Push back to origin
      run: |
        git remote add origin https://github.com/{{ cookiecutter.github_user }}/{{ cookiecutter.github_repo }}
        git push -f origin main
